/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
export {
  PREVIEW_WINDOW_NAME,
  CAPSULE_WINDOW_NAME,
  DISAPPEAR_INTERVAL,
  DEFAULT_TRIGGER_TYPE,
  LIGHT_NOTIFICATION_COLOR,
  DARK_NOTIFICATION_COLOR,
  AI_TRIGGER_TYPE,
  COLOR_TRANSPARENT,
  SELECT_DISPLAY_ID,
  INTENT_NAME_STOP,
  ERROR_CODE_NO_RECORDING
} from './types';

export { FreeScreenArea } from './types';

export { RecordManager } from './RecordManager';

export { WindowManager } from './WindowManager';

export { NotificationManager } from './NotificationManager';

export { MicManager } from './MicManager';

export { AccessManager } from './AccessManager';

export { RecorderFileManager } from './RecorderFileManager';

export { RecorderToast } from './RecorderToast';

export { PcRecordManager } from './PcRecordManager';

export { PcWindowManager } from './PcWindowManager';

export { IntentStopRecordImpl } from './IntentStopRecordImpl';