/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const COMMON_DELAY = 1000;

export const MOVING_DELAY = 2000;

export const TARGET_WINDOW_X = 512;

export const TARGET_WINDOW_Y = 1280;

export const TARGET_WINDOW_WIDTH = 256;

export const TARGET_WINDOW_HEIGHT = 128;

export const SWIPE_START_X = 300;

export const SWIPE_LEFT_END_X = 0;

export const SWIPE_START_Y = 2000;

export const SWIPE_END_X = 900;

export const SWIPE_END_Y = 2000;

export const DRAG_END_X = 1000;

export const DRAG_END_Y = 400;

export const BUNDLE_NAME = 'com.ohos.photos';

export const DELAY_BETWEEN_TESTS = 3500;

export const LOCK_SCREEN_X = 620;

export const LOCK_SCREEN_Y = 940;

export const POWER_KEY = 18;

export const SCREEN_OFF_DELAY = 5000;

export const CONTROL_MIC_Y = 1310;

export const CONTROL_TRACK_Y = 1480;

export const CONTROL_BUTTON_X = 990;

export const RECORDER_X = 630;

export const SCREENRECORDER_Y = 1660;

export const OUT_SHARE = 200;

export const SWITCH_LANGUAGE_DELAY = 4000;

export const SWIPE_X = 600;

export const SWIPE_Y= 2700;

export const SWIPE_Y_END= 0;

export const SWIPE_FAST = 20000;