/*
 * Copyright (c) Huawei Device Co., Ltd. 2026. All rights reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export class Constants {

  //无障碍重要性接口参数
  public static readonly ACCESSIBILITY_LEVEL_NO = 'no';
  public static readonly ACCESSIBILITY_LEVEL_YES = 'yes';
  public static readonly ACCESSIBILITY_LEVEL_NO_HIDE_DESCENDANTS = 'no-hide-descendants';
}